<a href="https://colab.research.google.com/github/leonardonels/Colab-python/blob/main/Esercizio_in_aula.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [96]:
%matplotlib inline
import matplotlib.pyplot as plt
import plotly.express as px

import numpy as np
import pandas as pd

1. Il file weather.csv contiene informazioni sul meteo di alcune citt√† australiane. Caricare il suo contenuto in un dataframe.

   Quante righe e quante colonne ci sono nel dataset?

   Ci sono valori mancanti?

In [23]:
weather = pd.read_csv('weather.csv',sep=';')
weather.head()

,Month,Location,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,1,Albury,20.4,37.6,0.0,54,0,7,46,17,1013.4,1009.2,3,26.1,36.7,No,No
1,1,Albury,20.9,33.6,0.4,50,9,17,54,30,1011.1,1008.4,8,24.8,31.7,No,Yes
2,1,Albury,18.4,23.1,2.2,48,11,39,62,67,1014.0,1014.8,8,21.8,19.5,Yes,Yes
3,1,Albury,17.3,23.7,15.6,39,9,17,74,65,1017.9,1016.5,8,19.2,21.6,Yes,Yes
4,1,Albury,15.5,22.9,6.8,31,6,9,92,63,1016.3,1013.9,8,17.2,22.2,Yes,No

In [27]:
weather.isnull().sum().sum()

0

In [28]:
weather.isnull().values.any()

False

2. Aggiungere al dataset:

- una nuova colonna "temp_diff" con la differenza in valore assoluto tra i valori di temperatura alle 9 del mattino e le 3 del pomeriggio

- una nuova colonna "hum_diff" con la differenza in valore assoluto tra i valori di umidit√† alle 9 del mattino e le 3 del pomeriggio

In [31]:
weather['temp_diff']=abs(weather['Temp9am']-weather['Temp3pm'])
weather['hum_diff']=abs(weather['Humidity9am']-weather['Humidity3pm'])
weather

,Month,Location,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,hum_diff,temp_diff
0,1,Albury,20.4,37.6,0.0,54,0,7,46,17,1013.4,1009.2,3,26.1,36.7,No,No,29,10.6
1,1,Albury,20.9,33.6,0.4,50,9,17,54,30,1011.1,1008.4,8,24.8,31.7,No,Yes,24,6.9
2,1,Albury,18.4,23.1,2.2,48,11,39,62,67,1014.0,1014.8,8,21.8,19.5,Yes,Yes,5,2.3
3,1,Albury,17.3,23.7,15.6,39,9,17,74,65,1017.9,1016.5,8,19.2,21.6,Yes,Yes,9,2.4
4,1,Albury,15.5,22.9,6.8,31,6,9,92,63,1016.3,1013.9,8,17.2,22.2,Yes,No,29,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14463,12,Uluru,22.1,35.8,63.8,43,17,31,77,41,997.8,995.2,2,26.0,33.5,Yes,No,36,7.5
14464,12,Uluru,22.6,36.8,0.0,50,30,15,63,39,1000.0,998.8,-1,29.7,34.0,No,No,24,4.3
14465,12,Uluru,23.2,38.0,0.0,33,17,17,25,14,1004.4,1001.0,-1,28.7,36.4,No,No,11,7.7
14466,12,Uluru,19.7,37.0,0.0,37,22,6,30,23,1004.6,1000.9,-1,28.2,35.1,No,No,7,6.9
14467,12,Uluru,23.7,33.0,0.0,46,24,17,40,38,1005.1,1002.7,-1,30.1,31.5,No,No,2,1.4

3. Selezionare soltanto le righe in cui "temp_diff" √® maggiore di 10 e "hum_diff" √® maggiore di 20. Qual √® la location in cui si verifica pi√π spesso questa elevata escursione termica (ovvero la location con il maggior numero di righe nella selezione)?

In [47]:
df=weather.groupby((weather['temp_diff']>10) & (weather['hum_diff']>20))

In [70]:
df['Location'].value_counts().head(1).index[0]

(False, 'Darwin')

4. Quante location sono presenti nel file?

In [77]:
weather['Location'].nunique()

42

In [80]:
len(weather['Location'].unique())

42

5. Trasformare i valori della colonna "RainToday" convertendo "yes" in 1 e "no" in 0. Utilizzando il metodo groupby calcolare per ogni location il numero di giorni di pioggia.

In [82]:
class_mapping = {
    'Yes': 1,
    'No': 0,
}
weather['RainToday']=weather['RainToday'].replace(class_mapping)
weather

<ipython-input-82-7da7c5755801>:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  weather['RainToday']=weather['RainToday'].replace(class_mapping)

,Month,Location,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,hum_diff,temp_diff
0,1,Albury,20.4,37.6,0.0,54,0,7,46,17,1013.4,1009.2,3,26.1,36.7,0,No,29,10.6
1,1,Albury,20.9,33.6,0.4,50,9,17,54,30,1011.1,1008.4,8,24.8,31.7,0,Yes,24,6.9
2,1,Albury,18.4,23.1,2.2,48,11,39,62,67,1014.0,1014.8,8,21.8,19.5,1,Yes,5,2.3
3,1,Albury,17.3,23.7,15.6,39,9,17,74,65,1017.9,1016.5,8,19.2,21.6,1,Yes,9,2.4
4,1,Albury,15.5,22.9,6.8,31,6,9,92,63,1016.3,1013.9,8,17.2,22.2,1,No,29,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14463,12,Uluru,22.1,35.8,63.8,43,17,31,77,41,997.8,995.2,2,26.0,33.5,1,No,36,7.5
14464,12,Uluru,22.6,36.8,0.0,50,30,15,63,39,1000.0,998.8,-1,29.7,34.0,0,No,24,4.3
14465,12,Uluru,23.2,38.0,0.0,33,17,17,25,14,1004.4,1001.0,-1,28.7,36.4,0,No,11,7.7
14466,12,Uluru,19.7,37.0,0.0,37,22,6,30,23,1004.6,1000.9,-1,28.2,35.1,0,No,7,6.9
14467,12,Uluru,23.7,33.0,0.0,46,24,17,40,38,1005.1,1002.7,-1,30.1,31.5,0,No,2,1.4

In [84]:
weather.groupby('Location')['RainToday'].sum()

Location
Adelaide             90
Albury               88
AliceSprings         39
BadgerysCreek        57
Ballarat            110
Bendigo              90
Brisbane             75
Cairns               88
Canberra             81
Cobar                48
CoffsHarbour         80
Dartmoor            126
Darwin               95
GoldCoast            65
Hobart               94
Melbourne            79
MelbourneAirport     96
Mildura              46
Moree                45
MountGambier        123
Nhil                 74
NorahHead            82
NorfolkIsland       122
Nuriootpa            89
PearceRAAF           77
Perth                91
PerthAirport         79
Portland            145
Richmond             61
Sale                 73
Sydney               83
SydneyAirport        84
Townsville           54
Tuggeranong          84
Uluru                37
WaggaWagga           86
Walpole             130
Watsonia             91
Williamtown          70
Witchcliffe         119
Wollongong           68
Woomera              31
Name: RainToday, dtype: int64

6. Creare una tabella pivot in cui per ogni location (sulle righe) e per ogni mese (sulle colonne) sia calcolata la temperatura massima media.

In [85]:
weather.pivot_table(index=['Location'], values=['MaxTemp'],columns=['Month'])

                    MaxTemp                                              \
Month                    1          2          3          4          5
Location
Adelaide          31.190323  29.289655  28.641935  24.826667  19.793548
Albury            31.487097  32.441379  30.790323  25.810000  18.077419
AliceSprings      34.858065  37.179310  35.148387  31.824138  25.370000
BadgerysCreek     28.792857  30.251724  29.412903  26.246667  23.225806
Ballarat          26.934483  26.288889  24.796667  20.093333  14.925806
Bendigo           30.100000  30.881481  28.996774  23.186667  17.045161
Brisbane          30.374074  32.303846  29.929032  28.783333  26.983871
Cairns            32.116667  33.248276  31.761290  30.431034  28.636842
Canberra          28.541935  29.306897  27.690323  23.880000  17.326667
Cobar             34.985714  35.841379  31.558621  28.666667  20.516129
CoffsHarbour      27.210345  28.457143  27.462069  25.879310  24.340000
Dartmoor          27.800000  25.582759  24.051613  21.220000  16.632258
Darwin            32.977419  33.482759  33.748387  34.526667  33.522581
GoldCoast         29.168421  29.672000  28.855000  27.485714  25.775862
Hobart            21.946429  23.775862  21.641935  20.426667  15.609677
Melbourne               NaN        NaN        NaN        NaN  18.593548
MelbourneAirport  27.174194  26.989655  25.661290  22.686667  18.122581
Mildura           33.322581  33.806897  31.909677  26.060000  20.356667
Moree             32.646667  35.803448  33.982609  30.423333  24.145161
MountGambier      27.429032  25.365517  23.996774  21.336667  16.636000
Nhil              31.567742  30.140741  28.419355  23.486667  18.193548
NorahHead         26.848276  27.710345  26.258065  24.430000  22.519355
NorfolkIsland     25.148276  25.965517  25.564286  24.503333  22.227586
Nuriootpa         30.374194  29.148276  27.906897  23.376667  18.258621
PearceRAAF        33.724138  34.250000  31.143333  25.080000  20.751613
Perth             31.843333  32.231034  29.645161  24.983333  20.841935
PerthAirport      32.422581  32.750000  29.983871  25.144828  20.809677
Portland          23.827586  22.182759  21.400000  20.016667  16.438710
Richmond          28.916129  30.103704  29.317857  26.730000  23.887097
Sale              23.744000  26.317857  23.986667  21.404762  18.628571
Sydney            27.726923  28.206897  26.793333  24.603571  22.728571
SydneyAirport     27.906452  28.375862  26.974194  24.806667  23.296667
Townsville        32.625806  33.448276  30.651613  31.050000  29.800000
Tuggeranong       27.686207  29.007407  27.044828  23.350000  17.080000
Uluru             37.311765  37.925000  35.829032  31.766667  24.993548
WaggaWagga        31.483871  32.565517  30.577419  26.236667  17.565517
Walpole           24.188000  24.506897  23.117241  20.496429  18.093103
Watsonia          28.303704  27.627586  26.200000  22.806667  18.441935
Williamtown       28.465517  29.068966  28.662963  25.470370  22.819355
Witchcliffe       28.654167  26.689655  25.720690  21.917857  18.693333
Wollongong        25.306452  25.650000  24.209677  23.100000  21.619355
Woomera           35.325806  34.862069  31.767742  27.893103  22.141935

                                                                         \
Month                    6          7          8          9          10
Location
Adelaide          16.043333  15.283871  17.658065  17.420000  20.993548
Albury            13.423333  13.280645  15.248387  16.823333  19.667742
AliceSprings      20.690000  21.080000  22.638710  24.620000  30.516667
BadgerysCreek     18.106667  18.483871  18.716129  21.093103  24.477419
Ballarat          10.551724  10.151613  11.803226  13.190000  15.556667
Bendigo           12.746667  12.812903  14.251613  15.520000  18.925806
Brisbane          21.526667  22.464516  23.153333  24.880000  27.083871
Cairns            27.413333  26.977419  26.600000  28.300000  30.100000
Canberra          13.013333  12.741935  14.258065  15.793333  18.477419
Cobar             15.153333  15.658065  17.277419  18.266667        NaN
CoffsHarbour      20.735714  20.076667  20.656667  22.953571  24.390323
Dartmoor          13.736667  13.296774  14.922581  15.390000  17.561290
Darwin            33.193333  31.545161  32.574194  33.176667  33.770968
GoldCoast         21.464286  21.744444  22.325926  23.792308  25.708000
Hobart            13.486667  13.150000  14.176667  16.230000  17.206452
Melbourne         14.223333  14.596774  15.912903  16.710000  19.254839
MelbourneAirport  13.523333  13.800000  15.177419  16.170000  18.519355
Mildura           15.866667  15.990323  17.977419  19.050000  23.487097
Moree             17.610000  18.083871  20.460000  20.175862  25.683871
MountGambier      13.493333  13.293548  14.989655  15.221429  17.711111
Nhil              14.176667  13.554839  15.677419  16.096667  19.380645
NorahHead         18.816667  18.516129  19.136667  20.876667  23.180645
NorfolkIsland     20.158621  19.870000  18.806452  20.225000  20.983333
Nuriootpa         13.686667  13.360714  15.532258  15.265517  19.090323
PearceRAAF        18.306667  17.555172  17.500000  18.662963  22.500000
Perth             18.580000  17.658065  17.693548  18.496667  21.845161
PerthAirport      18.558621  17.651613  17.474194  18.476667  21.958065
Portland          13.646667  13.267742  14.416129  14.696429  16.477419
Richmond          18.583333  18.512903  19.064516  21.700000  25.161290
Sale              14.491667  14.560000  15.716129  17.122222  20.055556
Sydney            18.864286  18.538710  19.148387  21.410345  23.657143
SydneyAirport     19.206667  19.003226  19.075862  21.486667  23.996774
Townsville        27.242857  26.045161  26.167742  29.396296  30.348148
Tuggeranong       12.796667  12.635484  14.154839  15.848276  18.814815
Uluru             19.540000  19.890323  22.545161  25.126667  30.806452
WaggaWagga        13.668966  13.393548  14.993548  16.296667  19.606667
Walpole           15.804167  15.414286  15.203571  15.417857  18.020000
Watsonia          13.790000  14.054839  15.441935  16.564286  18.950000
Williamtown       18.610000  18.435484  18.774194  21.392308  23.395455
Witchcliffe       16.503571  15.716129  15.722581  15.707143  18.417241
Wollongong        18.013333  17.829032  18.106452  19.443333  21.845161
Woomera           16.896667  17.609677  19.787097  20.703333  26.333333


Month                    11         12
Location
Adelaide          24.706667  28.658065
Albury            25.586667  30.500000
AliceSprings      35.383333  34.532000
BadgerysCreek     29.734483  32.369231
Ballarat          19.276667  24.596667
Bendigo           24.383333  28.664516
Brisbane          30.388889  30.058065
Cairns            31.939130  32.150000
Canberra          25.425926  28.716667
Cobar                   NaN        NaN
CoffsHarbour      25.978261  28.166667
Dartmoor          19.876667  24.354839
Darwin            33.736667  32.810345
GoldCoast         27.471429  28.683871
Hobart            18.580000  21.983871
Melbourne         20.806667  25.506452
MelbourneAirport  21.240000  26.316129
Mildura           27.960000  31.761290
Moree             31.571429  35.796667
MountGambier      19.717241  24.419231
Nhil              24.190000  29.019355
NorahHead         25.496667  26.961290
NorfolkIsland     21.982353  23.518750
Nuriootpa         24.213333  27.819355
PearceRAAF        29.660000  30.825806
Perth             27.680000  28.425806
PerthAirport      28.293333  29.300000
Portland          17.463333  21.055172
Richmond          29.906667  31.929032
Sale              21.216667  25.496774
Sydney            26.130000  28.129032
SydneyAirport     26.370000  28.848387
Townsville        32.175862  32.470370
Tuggeranong       24.950000  28.135484
Uluru             35.636667  35.035484
WaggaWagga        25.933333  31.433333
Walpole           20.813043  22.377419
Watsonia          21.593103  26.791304
Williamtown       27.480769  29.425000
Witchcliffe       23.218519  24.216129
Wollongong        23.665517  26.290000
Woomera           31.270000  32.585000

7. Visualizzare in un unico grafico la distribuzione dei valori di temperatura massima nel mese di maggio (5) e dicembre (12).

8. Visualizzare in uno scatterplot la relazione tra i valori di pressione e i valori di umidit√† (fare 2 plot distinti nella stessa figura, uno per i valori 9am e un altro per i valori 3pm). Colorare i punti di due colori diversi in base ai valori di RainToday.